import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, MapPin } from "lucide-react";
import { cities } from "../data/mock";

export function NewTrip() {
  const [step,setStep]=useState(1); const [name,setName]=useState("My next adventure"); const [budget,setBudget]=useState("80000"); const navigate=useNavigate();
  const next=()=>step<4?setStep(step+1):navigate("/trips/europe-adventure/builder");
  return <div className="mx-auto max-w-4xl space-y-7"><button onClick={()=>navigate("/dashboard")} className="inline-flex items-center gap-2 text-sm font-semibold text-black/50"><ArrowLeft size={16}/> Back to dashboard</button><div><div className="eyebrow">Create a trip</div><h1 className="mt-2 font-display text-4xl font-extrabold">Let’s map out your next story.</h1></div><div className="panel p-5 sm:p-8"><div className="mb-8 flex items-center justify-between gap-2">{["Basics","Destinations","Budget","Review"].map((s,i)=>{const n=i+1;return <div key={s} className="flex flex-1 items-center gap-2"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-bold ${n<=step?"bg-mint text-white":"bg-black/5 text-black/35"}`}>{n<step?<Check size={16}/>:n}</div><span className={`hidden text-xs font-bold sm:block ${n<=step?"text-ink":"text-black/35"}`}>{s}</span>{n<4&&<div className={`h-px flex-1 ${n<step?"bg-mint":"bg-black/10"}`}/>}</div>})}</div>
{step===1&&<div className="grid gap-5"><div><label className="mb-2 block text-sm font-bold">Trip name</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">Start date</label><input className="input" type="date" defaultValue="2026-06-10"/></div><div><label className="mb-2 block text-sm font-bold">End date</label><input className="input" type="date" defaultValue="2026-06-20"/></div></div><div><label className="mb-2 block text-sm font-bold">Description</label><textarea className="input min-h-28" placeholder="What kind of trip are you planning?"/></div></div>}
{step===2&&<div><p className="mb-4 text-sm text-black/50">Pick the cities you want to include.</p><div className="grid gap-3 sm:grid-cols-2">{cities.slice(0,4).map(c=><button key={c.id} className="flex items-center gap-3 rounded-2xl border border-black/10 p-3 text-left hover:border-mint"><img src={c.image} className="h-16 w-20 rounded-xl object-cover"/><div><b>{c.name}</b><p className="text-xs text-black/45">{c.country} · {c.costIndex}</p></div><MapPin className="ml-auto text-mint" size={17}/></button>)}</div></div>}
{step===3&&<div className="mx-auto max-w-xl"><label className="mb-2 block text-sm font-bold">Trip budget</label><div className="relative"><span className="absolute left-4 top-3 text-black/40">₹</span><input className="input pl-8 text-lg font-bold" value={budget} onChange={e=>setBudget(e.target.value)}/></div><div className="mt-5 rounded-2xl bg-[#eef6f2] p-5"><div className="text-xs font-bold text-mint">Planning target</div><p className="mt-1 text-sm text-black/60">We’ll keep your live estimate visible while you build the itinerary.</p></div></div>}
{step===4&&<div className="rounded-2xl bg-black/[.03] p-6"><div className="text-xs font-bold text-black/40">READY TO GO</div><h3 className="mt-2 font-display text-2xl font-bold">{name}</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><span className="text-xs text-black/40">Dates</span><p className="font-bold">10 — 20 Jun</p></div><div><span className="text-xs text-black/40">Cities</span><p className="font-bold">3 selected</p></div><div><span className="text-xs text-black/40">Budget</span><p className="font-bold">₹{Number(budget).toLocaleString("en-IN")}</p></div></div></div>}
<div className="mt-8 flex justify-between border-t border-black/5 pt-5"><button onClick={()=>setStep(Math.max(1,step-1))} className="btn-secondary" disabled={step===1}>Back</button><button onClick={next} className="btn-primary">{step===4?"Create trip":"Continue"} <ArrowRight size={16}/></button></div></div></div>;
}
