"""initial schema

Revision ID: 0001_initial
"""
from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('email',sa.String(255),nullable=False),sa.Column('password_hash',sa.String(512),nullable=False),sa.Column('profile_photo',sa.String(500)),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False)); op.create_index('ix_users_email','users',['email'],unique=True)
    op.create_table('user_preferences',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('preferred_currency',sa.String(8),nullable=False),sa.Column('travel_style',sa.String(40),nullable=False),sa.Column('preferred_categories',sa.JSON(),nullable=False),sa.Column('preferred_budget_level',sa.String(30),nullable=False)); op.create_index('ix_user_preferences_user_id','user_preferences',['user_id'],unique=True)
    op.create_table('cities',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('country',sa.String(120),nullable=False),sa.Column('region',sa.String(120),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('image_url',sa.String(500),nullable=False),sa.Column('cost_index',sa.Float(),nullable=False),sa.Column('popularity',sa.Float(),nullable=False),sa.Column('latitude',sa.Float(),nullable=False),sa.Column('longitude',sa.Float(),nullable=False)); op.create_index('ix_cities_name','cities',['name']); op.create_index('ix_cities_country','cities',['country'])
    op.create_table('trips',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(160),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('start_date',sa.Date(),nullable=False),sa.Column('end_date',sa.Date(),nullable=False),sa.Column('cover_photo',sa.String(500),nullable=False),sa.Column('budget',sa.Float(),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('is_public',sa.Boolean(),nullable=False),sa.Column('share_token',sa.String(128)),sa.Column('created_at',sa.DateTime(),nullable=False),sa.Column('updated_at',sa.DateTime(),nullable=False)); op.create_index('ix_trips_user_id','trips',['user_id']); op.create_index('ix_trips_share_token','trips',['share_token'],unique=True)
    op.create_table('activities',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('city_id',sa.Integer(),sa.ForeignKey('cities.id',ondelete='CASCADE'),nullable=False),sa.Column('name',sa.String(180),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('category',sa.String(50),nullable=False),sa.Column('duration_minutes',sa.Integer(),nullable=False),sa.Column('estimated_cost',sa.Float(),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('rating',sa.Float(),nullable=False),sa.Column('image_url',sa.String(500),nullable=False)); op.create_index('ix_activities_city_id','activities',['city_id']); op.create_index('ix_activities_name','activities',['name']); op.create_index('ix_activities_category','activities',['category'])
    op.create_table('stops',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('trip_id',sa.Integer(),sa.ForeignKey('trips.id',ondelete='CASCADE'),nullable=False),sa.Column('city_id',sa.Integer(),sa.ForeignKey('cities.id',ondelete='RESTRICT'),nullable=False),sa.Column('arrival_date',sa.Date(),nullable=False),sa.Column('departure_date',sa.Date(),nullable=False),sa.Column('sequence_order',sa.Integer(),nullable=False)); op.create_index('ix_stops_trip_id','stops',['trip_id'])
    op.create_table('trip_activities',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('stop_id',sa.Integer(),sa.ForeignKey('stops.id',ondelete='CASCADE'),nullable=False),sa.Column('activity_id',sa.Integer(),sa.ForeignKey('activities.id',ondelete='RESTRICT'),nullable=False),sa.Column('activity_date',sa.Date(),nullable=False),sa.Column('start_time',sa.Time(),nullable=False),sa.Column('end_time',sa.Time(),nullable=False),sa.Column('estimated_cost',sa.Float(),nullable=False),sa.Column('notes',sa.Text(),nullable=False),sa.Column('sequence_order',sa.Integer(),nullable=False)); op.create_index('ix_trip_activities_stop_id','trip_activities',['stop_id'])
    op.create_table('expenses',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('trip_id',sa.Integer(),sa.ForeignKey('trips.id',ondelete='CASCADE'),nullable=False),sa.Column('category',sa.String(50),nullable=False),sa.Column('amount',sa.Float(),nullable=False),sa.Column('currency',sa.String(8),nullable=False),sa.Column('expense_date',sa.Date(),nullable=False),sa.Column('description',sa.String(300),nullable=False)); op.create_index('ix_expenses_trip_id','expenses',['trip_id'])
def downgrade():
    for t in ['trip_activities','stops','expenses','activities','trips','cities','user_preferences','users']: op.drop_table(t)
